### ISSUE TITLE
Memory Usage Requirements?

### ISSUE THREAD

**Issue by nlin5** [lood339/SCCvSD#14]
Hi Dr. Chen,

Thank you for your contributions by providing this repository along with your paper. I am able to generate the train_data_10k.mat file containing pivot images, positive images, and cameras. However, when inputting that .mat file into network_train.py and running the script, I appear to run into memory limitations and the script is Killed. I was just wondering what the specs of your machine is when you trained the Siamese network?

Thanks

**Comment by lood339** [comment]
Hi nlin5,
    Thank you for interested in our work.
    It is quite strange to me that the program runs into memory limitation. The network and the input image resolution are quite small. Please double check that the input image size is 320x180. If your GPU has limited memory, please use small batch size to train the siemese network.
    Hope that helps.
