### ISSUE TITLE
How could I download the dataset of worldcup2014?

### ISSUE THREAD

**Issue by jiansheng1993** [lood339/SCCvSD#16]
How could I download the dataset of worldcup2014?

Thanks

**Comment by lood339** [comment]
This is the place: https://github.com/lood339/SCCvSD/tree/master/data/UoT_soccer
for world cup 2014 dataset.
Also, here is some description for the related data: https://github.com/lood339/SCCvSD/blob/master/data/read_me.py

**Comment by lood339** [comment]
Close this issue as the dataset link is provided.
