### ISSUE TITLE
where are these MAT-files generated from?

### ISSUE THREAD

**Issue by rambleramble** [lood339/SCCvSD#6]
Could you share where and how are these mat-files generated from?
https://github.com/lood339/SCCvSD/blob/474f5b612955fdb7c3c1f568cc39764533eeab74/data/read_me.py

Are these all based on the input of the UoT_soccer annotation from "Sports Field Localization Via Deep Structured Models"?

Thanks a lot!

**Comment by rambleramble** [comment]
The reason I am asking is that, for the deep features-based retrieval.
if I am using your preprocessed MAT "database_camera_feature.mat"  and "testset_feature",  the matching is very good.

However, in the 2nd approach, if I am training the Siamese network following your instruction in "bash network_train.sh" and generated "network.pth". and use the "fake_D.data" from the GAN approach as input to obtain the deep feature, the result is very off from the "testset_feature.mat", and the retrieval with "database_camera_feature.mat" does not give a satisfactory result as the 1st approach above.

**Comment by rambleramble** [comment]
Hi thanks a lot for the prompt reply. 
I think your TODO feature is exactly the missing piece.

Using both your "soccer_seg_detection"  and my own data, I observed the following:
(1) Your GAN-generated edge-image works fine with the HoG feature, and the NN search is correct with the groundtruth database.

(2) However, using the same GAN-generated edge-image, Siamese network feature can be generated but the NN search does not give the correct result. I suspect something was not correct when I implement the deep-feature extraction. Or at least not the same way which was used during the Siamese network training, which is exactly what you pointed out in TODO.

I am happy to implement this missing piece if possible.  Would be great if you could share the training data and necessary info.
Thanks again for your reply and this beautiful work!

**Comment by lood339** [comment]
Hi Rambleramble,
    No problem.
    Because I do not test the network training part, can you pull the code that works in your machine? So that, others may can use your code?
   Thank you.

Jimmy

**Comment by Explorerli** [comment]
Hi Rambleramble,
I'm following your discussions with Dr. Chen. Have you achieved the same results as Dr. Chen?  Could you shed some light on how to achieve this target?

1. For the network training part, are you using a 90K dataset(new "train_data_90k.mat") rather than default "train_data_10k.mat" generated in "generate_train_data.py"?
2. For the deep feature extracting part, are you using the method in "network_test.py" to obtain your own "testset_feature.mat"?

Thanks very much in advance!
Thanks very much also to Dr. Chen for sharing this code!

**Comment by rambleramble** [comment]
@lood339 , thank you!! 
At this moment, I haven't implemented any new code. I only tested the capability and it works well for my application. I will pull if any necessary new source is generated in the future.

@ Explorerli,  I uesd 10k version. which is already good enough for my application. deep feature extraction in "network_test.py" is for the 10K training data to be proceed to generate the database feature for the later stage retrieval. For the query image ( I assume input an RGB or BGR from your frame), you need to extract your own deep-feature, following the GAN-generated edgemap and the network_test.py implmenetaion of the ndarray example.  I think it shouldn't be too many  lines of code.

**Comment by Explorerli** [comment]
@rambleramble Thank you very much! I'll try!

**Comment by AhmedKhaled945** [comment]
@Explorerli Any luck with re-producing the same results in the paper by Dr.Chen?
Thanks in advance.
