### ISSUE TITLE
How to use "cv.findTransformECC"

### ISSUE THREAD

**Issue by Chen94yue** [lood339/SCCvSD#8]
I tried to solve the warning: "'Warning: find transform failed. Set warp as identity". But I failed. I run the code with opencv-pytorch-3.4.1.15. The error message is:
    _, warp = cv.findTransformECC(im_src, im_dst, warp, cv.MOTION_HOMOGRAPHY, criteria)
cv2.error: OpenCV(3.4.1) /io/opencv/modules/video/src/ecc.cpp:540: error: (-7) The algorithm stopped before its convergence. The correlation is going to be minimized. Images may be uncorrelated or non-overlapped in function findTransformECC

Is this function necessacy?

**Comment by lood339** [comment]
Yes, this function is necessary. It is used to optimized the camera pose (homography). The same error hits me in testing. So, I simply skip it by setting an identity matrix.

**Comment by Chen94yue** [comment]
Is there any effective solution?

**Comment by lood339** [comment]
In python, https://github.com/lood339/SCCvSD/blob/70c39728f0055f395ca5a494c3ff306c0e52c996/python/util/synthetic_util.py Line 59-66 is the solution. In C++, no effective solution.

**Comment by Chen94yue** [comment]
I understand this solution. But if you skip it by setting an identity matrix, the cv.findTransformECC function is not actually called, and you say this function is necessary. 🤷‍♂️

**Comment by lood339** [comment]
To make sure we are on the same page.
Case 1: When cv.findTransformECC works well, it is not skipped. warp is not an identify matrix.
Case 2: It is skipped only if the function fails.  warp is an identify matrix.
Most of examples are case 1, a few examples are case 2. So, I say it is necessary.
Hope that is clear.

**Comment by Chen94yue** [comment]
I mean, is it necessary for cv.findTransformECC to work well?

**Comment by lood339** [comment]
Nice, we are in the same page.
yes, ideally cv.findTransformECC should return an error flag instead of crash (c++ case). Except that, cv.findTransformECC works pretty well. I believe setting the warp as an identify matrix is a decent solution although it is not perfect.

**Comment by felibol** [comment]
I think so you can try to give more parameters  to cv.findTransformECC function as stated below link the last to params are not anymore optional. You can just call it like 
_, warp = cv.findTransformECC(im_src, im_dst, warp, cv.MOTION_HOMOGRAPHY, criteria, None, 5)
https://answers.opencv.org/question/212409/error-in-findtransformecc/

**Comment by calee88** [comment]
> I think so you can try to give more parameters to cv.findTransformECC function as stated below link the last to params are not anymore optional. You can just call it like
> _, warp = cv.findTransformECC(im_src, im_dst, warp, cv.MOTION_HOMOGRAPHY, criteria, None, 5)
> https://answers.opencv.org/question/212409/error-in-findtransformecc/

I followed felibol's solution and it worked. I think this issue can be closed.

**Comment by lood339** [comment]
Thanks @felibol for the fix and @calee88 for the conformation!
It is updated to the codebase.
